### PR TITLE
Containerize all the services

### PR DESCRIPTION
**Pull request by ravenkls**
I've put the frontend and backend into their own containers, I think I've done it correctly lol. It works on my machine.

It doesn't do hot-reloading on the frontend, although I'm not even sure if it even did that before.

I've also modified the readme to reflect the new method of setting up the containers.

👳🏿‍♂️

### CODE REVIEW

**Comment by AmritTalwar** [comment]
Hello @ravenkls, good work here.

Preferably for the backend service we could get nodemon to hot-reload inside the container, we should be able to do this by mounting the backend directory into the container as a volume (so that way changes on the dev machine will change the files in the container, allowing hot reloading in the container).

^^ See if you can create a container e.g. backend_development which allows hot reloading, would be mega useful.

**Comment by AmritTalwar** [comment]
Also, no need to worry about containerising the frontend yet, its nowhere near done lol (unless you would like to make a start on some components/ features 👀)

**Comment by ravenkls** [comment]
I've made it so nodemon can hot-reload now.

I thought it was already doing it because I had already mounted the backend directory in the container originally, but according to the [nodemon docs](https://github.com/remy/nodemon#application-isnt-restarting) you need to use the `--legacy-watch` flag you are working inside a container.

Also, surely there's no harm in containerising the frontend now anyway? It's going to have to be done eventually and it just removes any compatibility issues like I faced when I was trying to setup the backend to begin with.

**Comment by AmritTalwar** [comment]
@ravenkls apologies, didnt see that you had already mounted the volumes.

Work is already in progress to dockerise the backend (including start script changes that will make your current backend docker changes not work).

Could you remove all backend related changes from this PR please? The rest looks good to merge once this is done ✅

**Comment by AmritTalwar** [comment]
LGTM, merging in now. Nicely done @ravenkls 💯

**Pull request merged**
